sudo: false

language: c

os:
 - linux

compiler:
 - clang
 - gcc
 - g++

before_script:
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking
 - make check

env:
  global:
   - secure: "OyX+ypmU5NLRiSsIg1HvaGYvlaHSN2S/0AyCIQt63PNdcG7o1xa9Sv1Tcujr/xuvSvNbchNVEyBvCbNgqp/R8kRRhNPqFo2pxMMjkEKrJQqOm8sjvwMqTV4k6axEq+WwKylQaNJSDq1G9n5J/s7hlVPaiKAjsOPKnMN5ThNAr8o="

addons:
  coverity_scan:
    project:
      name: jedisct1/libsodium
      version: 1.0.13
      description: libsodium
      notification_email: coverityscan@pureftpd.org
      build_command_prepend: ./autogen.sh ; ./configure
      build_command: make -j4
      branch_pattern: coverity_scan
